// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetChatLog():Promise<Array<main.ChatLogEntry>>;

export function GetExtensionState():Promise<boolean>;

export function GetSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleExtension():Promise<boolean>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;
